apiVersion: v1
kind: Service
metadata:
  name: niche-greetings-d
  labels:
    app: niche-greetings-d
    service: niche-greetings-d
spec:
  selector:
    app: niche-greetings-d
  ports:
  - name: http
    port: 8080
    targetPort: 8080
