apiVersion: v1
kind: Service
metadata:
  name: niche-greetings-a
  labels:
    app: niche-greetings-a
    service: niche-greetings-a
spec:
  ports:
    - name: http
      port: 8080
  selector:
      app: niche-greetings-a
