apiVersion: apps/v1
kind: Deployment
metadata:
  name: niche-web
  labels:
    app: niche-web
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: niche-web
      version: v1
  template:
    metadata:
      labels: 
        app: niche-web
        version: v1
    spec:
      containers:
      - name: niche-web
        image: soline74/niche-web:dev-5c869b5
        env:
        - name: API_SERVICE
          value: "niche-configs"
        - name: API_PORT
          value: "8081"
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: KUBE_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBE_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        imagePullPolicy: Never
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: niche-web
  labels:
    app: niche-web
    service: niche-web
spec:
    ports:
      - name: http
        port: 8082
    selector:
      app: niche-web
---
