apiVersion: apps/v1
kind: Deployment
metadata:
  name: niche-api-v1
  labels:
    app: niche-api
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: niche-api
      version: v1
  template:
    metadata:
      labels:
        app: niche-api
        version: v1
    spec:
      containers:
      - name: niche-api
        image: soline74/niche-api:dev-99d4d10
        env:
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: KUBE_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBE_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
          limits:
            cpu: 300m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
        