apiVersion: apps/v1
kind: Deployment
metadata:
  name: niche-greetings-b
  labels:
    app: niche-greetings-b
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: niche-greetings-b
      version: v1
  template:
    metadata:
      labels:
        app: niche-greetings-b
        version: v1
    spec:
      containers:
      - name: niche-greetings-b
        image: soline74/niche-greetings-b:dev-e3aa376
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        env:
        - name: LOG_LEVEL
          value: info
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: niche-greetings-b
  labels:
    app: niche-greetings-b
    version: v1
spec:
  selector:
    app: niche-greetings-b
    version: v1
  ports:
  - name: http
    port: 8080
    targetPort: 8080
